// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBal(ctx context.Context, arg AddAccountBalParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccTransfers(ctx context.Context, debit int64) error
	DeleteAccount(ctx context.Context, accNumber int64) error
	DeleteAllTransactions(ctx context.Context, accNumber int64) error
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, accNumber int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, accNumber int64) (Account, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccTransactions(ctx context.Context, arg ListAccTransactionsParams) ([]Transaction, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	NewTransaction(ctx context.Context, arg NewTransactionParams) (Transaction, error)
	NewTransfer(ctx context.Context, arg NewTransferParams) (Transfer, error)
	UpdateaAccountBal(ctx context.Context, arg UpdateaAccountBalParams) (Account, error)
	UpdateaTransaction(ctx context.Context, arg UpdateaTransactionParams) error
}

var _ Querier = (*Queries)(nil)
