name: Bank Pro

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      psql:
        image: postgres
        env: 
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: omnibank
        ports:
          - 15432:5432

    steps:
    - name: Move code to runner
      uses: actions/checkout@v3

    - name: Create Go Migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /bin/
        which migrate

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run schema migration
      run: make migrateup

    - name: Test
      run: make test
